[phases.setup]
nixPkgs = ["php83", "php83Extensions.curl", "php83Extensions.mbstring", "php83Extensions.openssl", "php83Extensions.tokenizer", "php83Extensions.phar"]

[phases.install]
cmds = []

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"
